### ISSUE TITLE
Count’s Axis is shown as Number of records

### ISSUE THREAD

**Issue by kanitw** [vega/polestar#256]

**Comment by kanitw** [comment]
@domoritz  If you don’t have objection, I will simply change this to `COUNT`.

**Comment by domoritz** [comment]
What's the problem with "Number of records"?

**Comment by kanitw** [comment]
It's not consistent with field info and the special field name on the schema list.  

(Field Info used to show "Numbers of Records" but it's inconsistent with other function.) 

"Number of Records" seems friendly for Tableau users.  But I'm not sure for people who're new to Polestar/Voyager – which are probably our target users.
