### ISSUE TITLE
Test in other non-Chrome browsers. 

### ISSUE THREAD

**Issue by nyurik** [vega/polestar#291]
http://uwdata.github.io/polestar/#/ works in Chrome, but doesn't show properly in Firefox.

**Comment by domoritz** [comment]
@mpvartak Thank you for the issue. So far our focus has been on features but right now we are improving code quality and stability. Contributions are highly welcome.

**Comment by kanitw** [comment]
I renamed this issue to test in non-Chrome browsers.  

As @domoritz, we plan to only support using Polestar in Chrome.  But testing contribution are welcomed.
