### ISSUE TITLE
Logging & Transposing is reset with new mapping

### ISSUE THREAD

**Issue by domoritz** [vega/polestar#309]
Reproduce: 
* Acceleration on x
* Displacement on y
* Transpose
* cylinders on color
* boom

**Comment by kanitw** [comment]
Looks like something is wrong with the dataflow.  
Transpose is stateless, it should swap the location of the two pills.
But this seems like they are not updated

**Comment by kanitw** [comment]
Do you change anything related to the dataflow recently?

**Comment by domoritz** [comment]
Not that I know.

**Comment by kanitw** [comment]
Similar bug,

Try transpose and change mark type would also produce this bug.

**Comment by kanitw** [comment]
Moved to https://github.com/uwdata/voyager2/issues/72 as I want single list of TODO :)
