### ISSUE TITLE
Embed configuration. 

### ISSUE THREAD

**Issue by domoritz** [vega/polestar#311]
We want to be able to embed a polestar into an iframe and load a dataset. In embed mode, we would hide the dataset selector. What is the best way to initialize this mode? A magic global variable? A function that can be called on polestar? A tag that is added next to ng-app?

**Comment by kanitw** [comment]
Ideally we should decouple things a bit and don't include the module at all -- but maybe for this case magic global variable might suffice?

**Comment by domoritz** [comment]
You mean build a different version of the app? Yeah, that would be cool but
seems much more work. Also, how exactly would you do it?

**Comment by domoritz** [comment]
Temporarily solved.

**Comment by kanitw** [comment]
"Temporary solved" sounds like an issue that we should not close.

**Comment by domoritz** [comment]
"Closed for lack of better solution" would have been a better description

**Comment by domoritz** [comment]
Closing as it is working fine.
