### ISSUE TITLE
Displayed area is not tall enough

### ISSUE THREAD

**Issue by domoritz** [vega/polestar#322]
The large gray area should not be there. 

See it in https://vega.github.io/polestar/

<img width="1429" alt="screen shot 2015-09-13 at 17 02 06" src="https://cloud.githubusercontent.com/assets/589034/9839861/e8fe0eee-5a39-11e5-9687-477ee3d92b37.png">

**Comment by domoritz** [comment]
Seems to be related to me removing ui router.

**Comment by kadamwhite** [comment]
Also an issue with Vega

**Comment by domoritz** [comment]
This is not a vega issue. It used to work fine but I broke it at some point in the last weeks when I removed some libraries. You can check the deployed voyager version where it still works.

**Comment by kadamwhite** [comment]
My bad, typo: "Also an issue with Voyager," i meant

**Comment by domoritz** [comment]
Oh yeah. It should be fixed in vega-lite-ui (and that's also where I must have broken it).

**Comment by domoritz** [comment]
Replaced
