### ISSUE TITLE
Can't plot temporal field as date (Y/m/d)

### ISSUE THREAD

**Issue by dmitriyshashkin** [vega/polestar#348]
I'm trying to plot time-series data in the following format:

date,revenue
2015-10-18,100
2015-10-19,200
2015-10-20,110
2015-10-21,120

So, basically, I have a single value for each specific date and I want to output it in the same way, so each point would correspond to a single date and value.

I attach the revenue to y axis and date to x axis. Polestar recognizes "date" as temporal field and applies "MONTH" function to it. I've tried all other functions that are available for temporal values, yet failed to produce desired output. "_" option (which corresponds I suppose to not using any function at all) is clickable, but when I chose it polestar automatically switches back to using "MONTH" function.

I could specify the field with nominal, but such workaround produces another problem when I try to adjust the width of the plot in the generated vega-lite specification.

**Comment by kanitw** [comment]
Thank you for reporting, we will try to take a look ASAP (sometimes this week).

**Comment by domoritz** [comment]
Something about date is not working correctly. 

* We show the code instead of the values on labels
* You cannot select `-`

![date](https://cloud.githubusercontent.com/assets/589034/11223141/3be685b6-8d23-11e5-9c7d-53f442fba593.gif)

**Comment by domoritz** [comment]
Okay, I fixes the problems with the functions not working in https://github.com/vega/vega-lite/pull/743

You still cannot select `-`, though.
