### ISSUE TITLE
Loading Budget 2016 data breaks the schema viewer UI

### ISSUE THREAD

**Issue by jheer** [vega/polestar#353]
Load the Budget 2016 data set in PoleStar. The number of columns is extremely high (is it supposed to be this way?). Scrolling down, the columns continue past other page elements. I would expect that either (a) the other UI elements would extend all the way down along with the column names or (b) a local scroll region would be used to keep the rest of the page size fixed. I think (b) is probably the better solution.

**Comment by kanitw** [comment]
Thanks for helping us test.   I notice this earlier this week and planned to do it this weekend. 
The budget 2016 needs some wrangling so that it's in long format.  

Re the UI, agree that (b) is a better solution.

**Comment by domoritz** [comment]
Just noting that the problem with adding scroll has been that drag and drop breaks if we make the schema list scrollable. Potentially need to replace jquery-ui drag and drop with a custom implementation to make things work.
