### ISSUE TITLE
Crimea data not a good sample data set

### ISSUE THREAD

**Issue by jheer** [vega/polestar#354]
The PoleStar UI will let me load the crimea data, but this is not very good for demo purposes in its current format. The dates are in an unrecognized format, and the death counts are split across three fields. A better representation would be to have recognizable date strings and fold (reshape) the data to have "cause of death" and "death count" columns.

**Comment by kanitw** [comment]
- [ ] the broken date part is a part of https://github.com/uwdata/compassql/issues/91
- [ ] fold (reshape) the data to have "cause of death" and "death count" columns.
  - This requires checking if any example specs for vega and vega-lite has used this file.
