### ISSUE TITLE
Is it possible to share or export visualizations made in polestar?

### ISSUE THREAD

**Issue by aaronpowers** [vega/polestar#366]
I've been looking at the Polestar online demo and I'm wondering if it's possible to export or share visualizations made in it? Is there any way to take the visualizations made and use them somewhere else (e.g. get out vega or d3 code), or hyperlink to them so that someone else can see them?

Thank you! It's a very interesting tool.

**Comment by domoritz** [comment]
We will definitely add support for exporting soon (based on vega-embed). For now, click on the debug link on the bottom left and copy the vega-lite form there.

**Comment by domoritz** [comment]
Part of https://github.com/vega/polestar/issues/366

**Comment by kanitw** [comment]
This issue is #366

**Comment by aaronpowers** [comment]
Great! That sounds very cool. And thank you for the workaround.
