### ISSUE TITLE
Undo button while Data change

### ISSUE THREAD

**Issue by theharshbhatia** [vega/polestar#367]
Pressing Undo button after data change in polestart gh-pages at local, does reset the data but name remains the same.
e.g. 
We have cars data selected in data panel on left. Go select Barley data and then press undo button.
the fields of cars-data is populated in the data column but the name remains barley.
![screen shot 2016-05-23 at 11 31 40 am](https://cloud.githubusercontent.com/assets/2930973/15461616/f82b6fe4-20d9-11e6-8f95-e66ac3ea57c0.png)

**Comment by kanitw** [comment]
This won't be applicable for the new Voyager rebuilt in React.
