### ISSUE TITLE
Allow sort when there is 1-to-1 mapping between N and Q?

### ISSUE THREAD

**Issue by light-and-salt** [vega/polestar#372]
![raw](https://cloud.githubusercontent.com/assets/822034/17070590/9ee2c7fe-5011-11e6-8659-535230d214a9.png)

Right now if you have a scatterplot of a nominal field (N) and a quantitative field (Q), we do not show the sort button unless the quantitative field has aggregation. 

I understand why this is the case, because a nominal value could map to more than one quantitative values (e.g., in the picture above, a car name can be associated with multiple acceleration values). It doesn't make sense in this case to sort by the quantitative field as there are multiple Q values for each N value, but I think it still makes sense to sort by the nominal field (i.e., sort by car names, A-Z, Z-A). 

Further, if each N value only maps to one Q value, then sorting on the Q field (increasing, decreasing) will also make sense.

**Comment by kanitw** [comment]
This seems less important.  Filed to "later" milestone.
