### ISSUE TITLE
Show better error for empty columns on the first row

### ISSUE THREAD

**Issue by jdittrich** [vega/polestar#373]
**Usecase:** Using own (CSV) data
**What happens:** I open _change Data_ and paste a CSV in _add Dataset_. I give it a name and click "Add Data". The name appears in the left hand bar, however the variables do not change. On the javascript console I the following: 
`[Logging]  DATASET_NEW_PASTE mycustomdataname undefined vendor.js:358:17535`
`[Logging]  DATASET_CHANGE mycustomdataname undefined vendor.js:358:17535`
`Error: String(...).match(...) is null`
**Version:** The one provided on https://vega.github.io/polestar/ at the 31.7.2016 (probably  commit e630aaa )

**Comment by kanitw** [comment]
Can you provide your csv file in a pastebin?  That will help us debug this.

**Comment by jdittrich** [comment]
While trying to create a file that causes the error, I found the cause: Polestar crashes (or rather: fails silently) if the first column has an empty value. So that does not work:

```
"","B","C","D","E","F"
1,2,3,4,5,6
2,3,4,5,6,7
```

but this does:

```
"A","B","C","D","E","F"
1,2,3,4,5,6
2,3,4,5,6,7
```

**Comment by kanitw** [comment]
Thanks.  We might show better warning in the future.  Keep in mind that this is a research project, we assume that the input data should be reasonably clean.

**Comment by kanitw** [comment]
This will be considered as we're rebuilding [Voyager](https://github.com/vega/voyager) which will contain all features in PoleStar.
