### ISSUE TITLE
Long field-info blocks remove button

### ISSUE THREAD

**Issue by light-and-salt** [vega/polestar#374]
![long field-info](https://cloud.githubusercontent.com/assets/822034/17307146/77539c8e-57e8-11e6-9e06-b0133af2f9ad.png)

This means when `field-info` is long we cannot remove a field. https://github.com/vega/polestar/issues/250 can partially alleviate the problem but we should still make the 'x' button available.

**Comment by kanitw** [comment]
Duplicated of https://github.com/vega/vega-lite-ui/issues/94, I'm assign you to one in VLUI instead.
