### ISSUE TITLE
Ability to export from Polestar (like Lyra's)

### ISSUE THREAD

**Issue by georgeciobanu** [vega/polestar#382]
That would help with systems that don't integrate with Polestar but support Vega visualization.

**Comment by domoritz** [comment]
We have Debug -> Export to Lyra, which is currently broken unfortunately. Definitely something we are aiming for, though. We have this vision of being able to start with Voyager/Polestar, then exporting to Lyra, then so some final touch ups in the editor before exporting the visualization to the web.
