### ISSUE TITLE
gulp serve failed on master branch on windows 10

### ISSUE THREAD

**Issue by zhecui** [vega/polestar#383]
Hi all,

I have clone the master branch and tried to run on my local host. It seems both npm install and npm start does not work properly. I attached the output for npm start:

> polestar@0.14.0 start C:\Users\fs\Desktop\Zhe\Research\polestar-ps-master
> gulp serve

[14:38:55] Using gulpfile ~\Desktop\Zhe\Research\polestar-ps-master\gulpfile.js
[14:38:55] Starting 'styles'...
[14:38:56] Starting 'jshint'...
[14:38:56] gulp-inject 1 files into index.scss.

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: src\app\index.scss
Error: File to import not found or unreadable: ../../bower_components/angular-tooltips/dist/_angular-tooltips.scss
       Parent style sheet: stdin
        on line 10 of stdin
>> @import "../../bower_components/angular-tooltips/dist/_angular-tooltips.scss";
   ^

    at options.error (C:\Users\fs\Desktop\Zhe\Research\polestar-ps-master\node_modules\node-sass\lib\index.js:286:26)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Personal_ProgramFiles\\Nodejs\\node.exe" "C:\\Users\\fs\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! polestar@0.14.0 start: `gulp serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the polestar@0.14.0 start script 'gulp serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the polestar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs polestar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls polestar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\fs\Desktop\Zhe\Research\polestar-ps-master\npm-debug.log

The debug.log is 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Personal_ProgramFiles\\Nodejs\\node.exe',
1 verbose cli   'C:\\Users\\fs\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.1.2
3 info using node@v6.9.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle polestar@0.14.0~prestart: polestar@0.14.0
6 silly lifecycle polestar@0.14.0~prestart: no script for prestart, continuing
7 info lifecycle polestar@0.14.0~start: polestar@0.14.0
8 verbose lifecycle polestar@0.14.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle polestar@0.14.0~start: PATH: C:\Users\fs\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\fs\Desktop\Zhe\Research\polestar-ps-master\node_modules\.bin;C:\Personal_ProgramFiles\Python\;C:\Personal_ProgramFiles\Python\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Dell\Dell Data Protection\Access\Advanced\Wave\Gemalto\Access Client\v5\;C:\Program Files (x86)\Security Innovation\SI TSS\bin\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Personal_ProgramFiles\MatLab\bin;C:\Program Files\Java\jdk1.8.0_45\bin;C:\Program Files\Java\jdk1.8.0_45\jre\bin;C:\Program Files\Tomcat\apache-tomcat-8.0.14\lib;C:\Program Files\Tomcat\apache-tomcat-8.0.14\bin;C:\Personal_ProgramFiles\Python;C:\Personal_ProgramFiles\MinGW\bin;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Personal_ProgramFiles\MiKTeX\miktex\bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Personal_ProgramFiles\PhantomJS\bin\;C:\Personal_ProgramFiles\Cmake\bin;C:\Program Files\CMake\bin;C:\Personal_ProgramFiles\Nodejs\;C:\Personal_ProgramFiles\Git\cmd;C:\Ruby200-x64\bin;C:\Users\fs\AppData\Local\Enthought\Canopy\User;C:\Users\fs\AppData\Local\Enthought\Canopy\User\Scripts;C:\Users\fs\AppData\Local\Microsoft\WindowsApps;C:\Users\fs\AppData\Roaming\npm
10 verbose lifecycle polestar@0.14.0~start: CWD: C:\Users\fs\Desktop\Zhe\Research\polestar-ps-master
11 silly lifecycle polestar@0.14.0~start: Args: [ '/d /s /c', 'gulp serve' ]
12 silly lifecycle polestar@0.14.0~start: Returned: code: 1  signal: null
13 info lifecycle polestar@0.14.0~start: Failed to exec start script
14 verbose stack Error: polestar@0.14.0 start: `gulp serve`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\fs\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\fs\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid polestar@0.14.0
16 verbose cwd C:\Users\fs\Desktop\Zhe\Research\polestar-ps-master
17 error Windows_NT 10.0.14393
18 error argv "C:\\Personal_ProgramFiles\\Nodejs\\node.exe" "C:\\Users\\fs\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.5
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error polestar@0.14.0 start: `gulp serve`
22 error Exit status 1
23 error Failed at the polestar@0.14.0 start script 'gulp serve'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the polestar package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp serve
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs polestar
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls polestar
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Can anyone help with this? Thanks!

**Comment by kanitw** [comment]
We're in the process of refactoring [Voyager 2](http://idl.cs.washington.edu/papers/voyager2) into a [React/Redux app](https://github.com/vega/voyager/tree/vy2).  Voyager 2 will contain all features in Polestar plus more recommendation features and thus will subsume this project. 
This process will also produce a way more stable codebase. so this problem should disappear. 

We should have a workable version in a month or two, so you might want to re-check again later.
