### ISSUE TITLE
Potential to get this running against latest jupyterlab?

### ISSUE THREAD

**Issue by Analect** [vega/polestar#385]
I can see there hasn't been much activity in here for a while.  I was just wondering if there are any plans to get polestar working in conjunction with jupyterlab.  Of all the visualisation tools out there for that ecosystem, I'm not aware of another one that allows for drag/dropping of data-series as per polestar. Thanks.

**Comment by kanitw** [comment]
Thanks for asking.  Please follow our development of the new version of [Voyager](https://github.com/vega/voyager), which contains all features in PoleStar.  We are planning to make Voyager available as a component that can be embedded in other applications (including JupyterLab.)
